Models/ErrorViewModel.cs
namespace NoteSandbax.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Notes.cs
using System.ComponentModel.DataAnnotations;

namespace NoteSandbax.Models
{
    public class Notes
    {
        [Key]
        public int Id { get; set; }
        public string Subject { get; set; }
        public string body { get; set; }

    }
}

ViewModels/MainViewViewModel.cs
using NoteSandbax.Models;

namespace NoteSandbax.ViewModels
{
    public class MainViewViewModel
    {
        public IEnumerable<Notes> notes { get; set; }
    }
}

ViewModels/NoteDetailsViewModel.cs
using NoteSandbax.Models;

namespace NoteSandbax.ViewModels
{
    public class NoteDetailsViewModel
    {
        public Notes note { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NoteSandbax.Models;
using System.Diagnostics;

namespace NoteSandbax.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NoteSandbax.Data;
using NoteSandbax.Interfaces;
using NoteSandbax.Models;
using NoteSandbax.ViewModels;

namespace NoteSandbax.Controllers
{
    public class NotesController : Controller
    {
        private readonly INotesRepository _noteRepository;

        public NotesController(INotesRepository noteRepository)
        {
            _noteRepository = noteRepository;
        }

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            IEnumerable<Notes> _notes = await _noteRepository.GetAll();

            if(_notes == null)
            {
                return NotFound();
            }

            var viewModel = new MainViewViewModel
            {
                notes = _notes
            };
        
            return View(viewModel);
        
        
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int id)
        {
            Notes note = await _noteRepository.GetNote(id);
            
            if (note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        // GET: Notes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Subject,body")] Notes notes)
        {
            if (ModelState.IsValid)
            {
                _noteRepository.Add(notes);
                return RedirectToAction(nameof(Index));
            }
            return View(notes);
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (_noteRepository.NoteExists(id) == false)
            {
                return NotFound(); //   make my own not found page!
            }

            var notes = await _noteRepository.GetNote(id);
            if (notes == null)
            {
                return NotFound();
            }
            return View(notes);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Subject,body")] Notes notes)
        {
            if (id != notes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _noteRepository.Update(notes);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotesExists(notes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(notes);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (_noteRepository.NoteExists(id) == false)
            {
                return NotFound(); //   make my own not found page!
            }

            var notes = await _noteRepository.GetNote(id);
            if (notes == null)
            {
                return NotFound();
            }

            return View(notes);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_noteRepository.NoteExists(id) == false)
            {
                return Problem("Entity set 'AppDbContext.Notes'  is null.");
            }
            var notes = await _noteRepository.GetNote(id);
            if (notes != null)
            {
                _noteRepository.Delete(notes);
            }
            return RedirectToAction(nameof(Index));
        }

        private bool NotesExists(int id)
        {
            return _noteRepository.NoteExists(id);
        }

        public IActionResult GetNoteDetailsViewComponent(int id)
        {
            return ViewComponent("NoteDetails", id);
        }

        //  Route annotations aren't needed
        //[Route("Notes/NoteDetails")]
        //[Route("Notes/NoteDetails/{id?}")]
        public PartialViewResult NoteDetails(int id)
        {
            Thread.Sleep(500);
            Notes note =  _noteRepository.GetSingle(id);
            return PartialView("_NoteDetails", note);
        }


        // GET: Notes/GetEdit/5
        public async Task<IActionResult> GetEdit(int id)
        {
            if (_noteRepository.NoteExists(id) == false)
            {
                return NotFound(); //   make my own not found page!
            }

            var notes = await _noteRepository.GetNote(id);
            if (notes == null)
            {
                return NotFound();
            }
            Thread.Sleep(500);
            return PartialView("_NoteEdit", notes);
        }


        // GET: Notes/GetDelete/5
        public async Task<IActionResult> GetDelete(int id)
        {
            if (_noteRepository.NoteExists(id) == false)
            {
                return NotFound(); //   make my own not found page!
            }

            var notes = await _noteRepository.GetNote(id);
            if (notes == null)
            {
                return NotFound();
            }
            Thread.Sleep(500);
            return PartialView("_NoteDelete", notes);
        }

        // GET: Notes/GetCreate
        public IActionResult GetCreate()
        {
            Thread.Sleep(500);
            return PartialView("_NoteCreate");
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}


<div class="text-center">
    <div class="text-8xl p-4">NANA</div>
    <p class="text-4xl">Not Another Notes App</p>
    </br>
    <hr />
    </br>

    <p class="text-4xl mb-2">I used this project to learn about:</p>
    </br>
    <div>
        <ul >
            <li >- Implementing partial views and view components</li>
            <li >
                - Implementing CRUD actions via models using:

                <ul >
                    <li>
                        * Javascript
                    </li>
                    <li>
                        * JQuery
                    </li>
                    <li>
                        * Ajax
                    </li>
                </ul>
            </li>
            <li >
                - Implementing DaisyUI
                <ul>
                    <li>** DaisyUI Is a framework built on TailwindCSS</li>
                </ul>
            </li>
            <li >- This was made in ASP .Net MVC</li>
        </ul>
    </div>

</div>

Views/Notes/Create.cshtml
@model NoteSandbax.Models.Notes

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Notes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="body" class="control-label"></label>
                <input asp-for="body" class="form-control" />
                <span asp-validation-for="body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Notes/Delete.cshtml
@model NoteSandbax.Models.Notes

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Notes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.body)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Notes/Details.cshtml
@model NoteSandbax.Models.Notes

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Notes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.body)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Notes/Edit.cshtml
@model NoteSandbax.Models.Notes

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Notes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="body" class="control-label"></label>
                <input asp-for="body" class="form-control" />
                <span asp-validation-for="body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Notes/Index.cshtml
@using NoteSandbax.ViewModels
@model MainViewViewModel

@{
    ViewData["Title"] = "Index";
}

<div class="text-center flex text-5xl my-4 tooltip tooltip-bottom tooltip-error" data-tip="Doesn't this graphic remind you of the good ole days when we all still used Myspace">
    <img src="http://malagasang3es.weebly.com/uploads/8/7/8/9/87899022/source_orig.gif" width="400px" class="text-center p-4 mx-auto" />
</div>

<div class=" border bg-base-300 p-4">
    <table class="table mx-auto p-4">
        <!-- head -->
        <thead>
            <tr>
                <th>Id</th>
                <th>Subject</th>
               @* <th>Body</th>*@
                <th><a class="btn btn-sm" onclick="loadCreate()" >Add Note</a> </th>
            </tr>
        </thead>
        <tbody>
           

            @foreach (var item in Model.notes)
            {
                <tr>
                    <th>@Html.DisplayFor(modelItem => item.Id)</th>
                    <td>@Html.DisplayFor(modelItem => item.Subject)</td>
                    @*<td>@Html.DisplayFor(modelItem => item.body)</td>*@
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-sm" onclick="loadDetails(@item.Id)" >Details</a>
                            <a class="btn btn-sm" onclick="loadEdit(@item.Id)">Edit</a>
                            <a class="btn btn-sm" onclick="loadDelete(@item.Id)">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="mx-auto" id="detailHolder">
        
    </div>
</div>
 

Views/Shared/_Footer.cshtml
<!-- FOOTER -->
<div id="footer" class="mb-0">
    <!-- CONTAINER -->
    <div class="container flex flex-col-reverse justify-between px-6 py-10 mx-auto space-y-8 md:flex-row md:space-y-0">
        <!-- LOGO AND SOCIAL LINKS CONTAINER -->
        <div class="flex flex-col-reverse items-center justify-between space-y-12 md:flex-col md:space-y-0 md:items-start">
            <div class="mx-auto my-6 text-center md:hidden">
                COPYRIGHT &copy; 2022, ALL Rights Reserved
            </div>

           
        </div>
        <!-- LIST CONTAINER -->
        <div class="flex justify-around space-x-32">
            <div class="flex flex-col space-y-3 text-center">
                <a href="#" class="">These</a>
                <a href="#" class="">Buttons</a>
                <a href="#" class="">Do</a>
                <a href="#" class="">Nothing</a>
            </div>
            <div class="flex flex-col space-y-3 text-center">
                <a href="#" class="">I</a>
                <a href="#" class="">Promise</a>
                <a href="#" class="">You</a>
            </div>
        </div>
        <!-- INPUT CONTAINER -->
        <div class="flex flex-col justify-between">
            <form>
                <div class="flex space-x-3">
                    <input type="text"
                            class="flex-1 px-4 rounded-full focus:outline-none"
                            placeholder="You can try to input information here but it won't do anything!'" />
                    <button class="px-6 py-2 rounded-full focus:outline-none">
                        GO
                    </button>
                </div>
            </form>
            <!-- COPYRIGHT -->
            <div class="hidden md:block">
                COPYRIGHT &copy; 2022, ALL Rights Removed because its 2022
            </div>
        </div>

    </div>
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html id="html" lang="en" data-theme="night">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
  
    <link href="~/css/output.css"  rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.15.2/dist/full.css" rel="stylesheet" type="text/css" />

</head>

<body class="container mx-auto content-center align-content-between"> 

    <partial name="_NavBar.cshtml"  />
    
    @RenderBody()

   
    <partial name="_Footer.cshtml"/>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<div class="navbar bg-base-100">
    <div class="flex-1">
        <a class="btn btn-ghost normal-case text-xl" asp-controller="Home" asp-action="Index">Home</a>
    </div>
    <div class="flex-none">
        <ul class="menu menu-horizontal p-0">
            <li><a asp-controller="Notes" asp-action="Index">Notes</a></li>
            <li tabindex="10">
                <a>
                    Themes
                    <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" /></svg>
                </a>
                <ul class="p-2 bg-base-100 z-10">
                    <li><a value='light' onclick="themeSwitch('light');" >Light</a></li>
                    <li><a value='dark' onclick="themeSwitch('dark');" >Dark</a></li>
                    <li><a value='dracula' onclick="themeSwitch('dracula');" >Dracula</a></li>
                    <li><a value='night' onclick="themeSwitch('night');" >Night</a></li>
                    <li><a value='pastel' onclick="themeSwitch('pastel');" >Pastel</a></li>
                    <li><a value='coffee' onclick="themeSwitch('coffee');" >Coffee</a></li>
                    <li><a value='business' onclick="themeSwitch('business');" >Business</a></li>
                    <li><a value='luxury' onclick="themeSwitch('luxury');" >Luxury</a></li>
                    <li><a value='aqua' onclick="themeSwitch('aqua');" >Aqua</a></li>
                    <li><a value='retro' onclick="themeSwitch('retro');" >Retro</a></li>
                    <li><a value='synthwave' onclick="themeSwitch('synthwave');" >Synthwave</a></li>
                    <li><a value='cupcake' onclick="themeSwitch('cupcake');" >Cupcake</a></li>
                    <li><a value='emerald' onclick="themeSwitch('emerald');" >Emerald</a></li>

                </ul>
            </li>
        </ul>
    </div>
</div>

Views/Shared/_NoteCreate.cshtml
@model NoteSandbax.Models.Notes


<!-- Put this part before </body> tag -->
<input type="checkbox" id="detailModal" class="modal-toggle" />
<div id="" class="modal modal-open">
    <div class="modal-box relative">
        <label for="my-modal-3" onclick="closeDetails()" class="btn btn-sm btn-circle absolute right-2 top-2">✕</label>
        <h3 class="text-lg font-bold">Create a new Note!</h3>
        <p class="py-4">

            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group p-2">
                           
                            <input asp-for="Subject" type="text" placeholder="Subject" class="input input-bordered input-primary w-full max-w-xs" />
                            <span asp-validation-for="Subject" class="text-danger"></span>
                        </div>
                        <div class="form-group p-2">
                           
                            <textarea type="text" asp-for="body" placeholder="Note body"  class="textarea textarea-primary" cols="42" rows="5"></textarea>
                            <span asp-validation-for="body" class="text-danger"></span>
                        </div>
                        <div class="form-group p-2">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

        </p>
    </div>
</div>

Views/Shared/_NoteDelete.cshtml
@model NoteSandbax.Models.Notes





<!-- Put this part before </body> tag -->
<input type="checkbox" id="detailModal" class="modal-toggle" />
<div id="" class="modal modal-open  ">
    <div class="modal-box relative">
        <label for="my-modal-3" onclick="closeDetails()" class="btn btn-sm btn-circle absolute right-2 top-2">✕</label>
        <h3 class="text-lg font-bold">Sure you want to DELETE Note?</h3>
        <p class="py-4">
            <img src="https://cdn.dribbble.com/users/2124240/screenshots/6118828/delete_icon_intraction.gif" width="200px" class="text-center p-2 mx-auto" />
            <h3 class="text-lg font-bold">@Model.Subject</h3>
        <p class="py-4">@Model.body</p>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-error" />
        </form>

        </p>


    </div>
</div>

Views/Shared/_NoteDetails.cshtml
@model NoteSandbax.Models.Notes

@*
<div class="card w-96 bg-base-100 shadow-xl image-full text-center p-4 mx-auto">
    <figure><img src="https://media.istockphoto.com/photos/blank-note-picture-id471399483?b=1&k=20&m=471399483&s=170667a&w=0&h=bBZex4OKDcSNZFl0pj0Q6Bxey4G19FSOG8Kw35UoZhg=" /></figure>
    <div class="card-body">
        <button class="btn-sm right-0" onclick="closeDetails()">X</button>
        <h2 class="card-title">@Model.Subject</h2>
        <p>@Model.body</p>

    </div>
</div>

*@

<!-- Put this part before </body> tag -->
<input type="checkbox" id="detailModal" class="modal-toggle" />
<div id="ddd" class="modal modal-open">
    <div class="modal-box relative">
        <label for="my-modal-3" onclick="closeDetails()" class="btn btn-sm btn-circle absolute right-2 top-2">✕</label>
        <h3 class="text-lg font-bold">@Model.Subject</h3>
        <p class="py-4">@Model.body</p>
    </div>
</div>

Views/Shared/_NoteEdit.cshtml
@model NoteSandbax.Models.Notes




<!-- Put this part before </body> tag -->
<input type="checkbox" id="detailModal" class="modal-toggle" />
<div id="" class="modal modal-open">
    <div class="modal-box relative">
        <label for="my-modal-3" onclick="closeDetails()" class="btn btn-sm btn-circle absolute right-2 top-2">✕</label>
        <h3 class="text-lg font-bold">Editing: @Model.Subject</h3>
        <p class="py-4">

            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group p-2">
                            
                            <input asp-for="Subject" class="input input-bordered input-primary w-full max-w-xs" placeholder="@Model.Subject"/>
                            <span asp-validation-for="Subject" class="text-danger"></span>
                        </div>
                        <div class="form-group p-2">
                           
                            <textarea type="text" asp-for="body" class="textarea textarea-primary" cols="42" rows="5" placeholder="@Model.body" ></textarea>
                            <span asp-validation-for="body" class="text-danger"></span>
                        </div>
                        <div class="form-group p-2">
                            <input type="submit" value="Save" class="btn btn-info" />
                        </div>
                    </form>
                </div>
            </div>


        </p>
    </div>
</div>